server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: stark
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true